services:
  server:
    build: ./server
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./server:/app
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: items
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - container_network
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - item-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: items
    networks:
      - container_network
volumes:
  item-mysql-data:
networks:
  container_network:

  # client:
  #   build: ./client
  #   ports:
  #     - 127.0.0.1:5000:5000
  #   working_dir: /app/client
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./client:/app/client
  #   environment:
  #     SERVER_IP: 127.0.0.1
  #     SERVER_PORT: 3000
  #   networks:
  #     - my-network
  #   depends_on:
  #     - server