"""create user table

Revision ID: 06d743706ab4
Revises: 7a977d4d1674
Create Date: 2023-08-08 16:20:20.246110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '06d743706ab4'
down_revision: Union[str, None] = '7a977d4d1674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('email', sa.String(64), nullable=False),
        sa.Column('password', sa.String(64), nullable=True),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'])
    op.create_unique_constraint('unique_user_email', 'users', ['email'])
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('items_owner_fk', 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_owner_fk', 'items', type_='foreignkey')
    op.drop_constraint('unique_user_email', 'users', type_='unique')
    op.drop_column('items', 'owner_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
