"""create context table

Revision ID: c1c8aa86eeec
Revises: 06d743706ab4
Create Date: 2023-08-09 15:54:37.741176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c8aa86eeec'
down_revision: Union[str, None] = '06d743706ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contexts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(64)),
        sa.Column("description", sa.String(64)),
        sa.Column("owner_id", sa.Integer()),
    )
    op.create_index(op.f("ix_contexts_id"), "contexts", ["id"])
    op.create_unique_constraint(
        "unique_context_name",
        "contexts",
        ["name", "owner_id"]
    )
    op.add_column("items", sa.Column("context_id", sa.Integer()))
    op.create_foreign_key(
        "items_context_fk",
        "items",
        "contexts",
        ["context_id"],
        ["id"],
        ondelete="CASCADE"
    )
    op.create_foreign_key(
        "contexts_owner_fk",
        "contexts",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("items_context_fk", "items", type_="foreignkey")
    op.drop_constraint("contexts_owner_fk", "contexts", type_="foreignkey")
    op.drop_constraint("unique_context_name", "contexts", type_="unique")
    op.drop_column("items", "context_id")
    op.drop_index(op.f("ix_contexts_id"), table_name="contexts")
    op.drop_table("contexts")
    # ### end Alembic commands ###
